#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

mkdir "$install_dir/data"

chown -R "$app:$app" "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Cronjob management UI" --log=systemd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path=systemd --wait_until="Ready"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation complete."
