#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace

mkdir "$install_dir/.build"

mv "$install_dir"/* "$install_dir/.build"

chown -R "$app:$app" "$install_dir/.build"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Updating system configurations..."

ynh_config_add_nginx

ynh_config_add_logrotate

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building $app... This will take some time."

pushd $install_dir/.build
	ynh_hide_warnings corepack enable pnpm
	ynh_hide_warnings pnpm install
	ynh_hide_warnings ynh_exec_as_app pnpm -F pl-api build
	ynh_hide_warnings ynh_exec_as_app pnpm -F nicolium build
popd

mv $install_dir/.build/packages/nicolium/dist/* $install_dir/
ynh_safe_rm "$install_dir/.build"
ynh_safe_rm "$install_dir/.cache"
ynh_safe_rm "$install_dir/.local"
ynh_safe_rm "$install_dir/.npm"
chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade complete."
